### ISSUE TITLE
"A" and "I" should operate on the visual selection, not the line (visual mode)

### ISSUE THREAD

**Issue by guillermooo** [sublimehq/Vintage#82]
To match Vim's behavior, "A" and "I" should place the caret at the edge of the current selection, not the underlying line.

**Comment by misfo** [comment]
It seems strange, but it looks like Vim (7.3, MacVim for me) only goes to the edge of the selection (instead of beginning/end of line) in these cases:
- For `I`, when the selection spans multiple lines and is made backwards
- For `A`, when the selection is within one line or when the selection is made forwards

**Comment by guillermooo** [comment]
Yep, c onfirmed. I don't see how that behavior's useful, though... Would it be worth trying to follow that on ST too?

**Comment by misfo** [comment]
Probably not. Is there another visual mode command in Vim that reliably switches to insert mode at the boundaries of the selection? This would be really handy, for example, after making multiple selections with `cmd+d`.

**Comment by misfo** [comment]
I opened a pull request for `I` and `A` that work as you described. If someone really finds Vim behavior useful, we could always implement a setting that reproduces it...

**Comment by guillermooo** [comment]
Okies. Closing this. Thanks, misfo!
